name: Build Dist

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            fail-fast: false
            matrix:
                os:
                    - ubuntu-latest
                    - macos-latest
                    - windows-latest
                python-version:
                    - "3.10"
                    - "3.11"

        steps:
            - name: Checkout repository content
              uses: actions/checkout@v3

            - name: Setup Python Version
              uses: actions/setup-python@v4
              with:
                  python-version: "${{ matrix.python-version }}"

            - name: Install Requirements
              run: |
                  python -m pip install --upgrade pip
                  python -m pip install --upgrade pip requests
                  python -m pip install -r requirements_dev.txt

            - name: Make Dist
              run: python setup.py sdist bdist_wheel

            - name: Upload Dist
              uses: actions/upload-artifact@v1
              with:
                  name: CLS-Python Distribution
                  path: dist/
