name: Build Docs

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    docs:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository content
              uses: actions/checkout@v3

            - name: Setup python version
              uses: actions/setup-python@v4
              with:
                  python-version: "3.10"

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  python -m pip install sphinx

            - name: Upgrade pip, install package, install requirements, build docs
              run: |
                  pip install --upgrade pip
                  pip install .
                  pip install -r ./docs/requirements.txt
                  pip install sphinx
                  sphinx-build docs ./docs/_build/html/

            - name: Upload Docs
              uses: actions/upload-artifact@v1
              with:
                  name: CLS-Python Documentation
                  path: docs/_build/html/
